/** Report page behaviour: mounts the Executive Shell from the embedded JSON. */
import { mountExecShell } from './exec-shell.js';

const data = JSON.parse(document.getElementById('report-data').textContent);
const p = (v) => (v < 0.001 ? '< 0.001' : v.toFixed(3));

const shell = mountExecShell({
  title: 'Pymaceuticals Study Analysis',
  tagline: `The mouse-study exercise done with the tests it implies: a cleaned merge with the duplicate rule stated, per-regimen statistics, IQR outliers, a weight-volume regression that reports what the data say, one-way ANOVA with Tukey HSD across four regimens, and Kaplan-Meier time in study with log-rank tests. Generated by CI from the vendored files.`,
  repo: 'https://github.com/Freddricklogan/MedicalTreatment-Analytics',
  pagesUrl: 'https://freddricklogan.github.io/MedicalTreatment-Analytics/',
  badges: [{ label: 'ANOVA · Tukey · Kaplan-Meier', tone: 'accent' }, { label: 'statsmodels + scipy', dot: true }, { label: 'Measured in CI', dot: true }],
  kpis: [
    { label: 'Mice', compute: () => data.mice, tone: 'accent' },
    { label: 'Lowest mean volume', compute: () => `${data.lowestMeanRegimen} ${data.lowestMean.toFixed(2)}`, tone: 'ok' },
    { label: 'ANOVA F (p)', compute: () => `${data.anovaF.toFixed(1)} (${p(data.anovaP)})` },
    { label: 'Weight–volume r (p)', compute: () => `${data.regressionR.toFixed(3)} (${p(data.regressionP)})`, tone: 'warn' },
    { label: 'Dropped mice', compute: () => data.dropped.length, tone: 'muted' }
  ],
  tour: [
    { selector: '.pm-note', title: 'What this page is', body: `${data.mice} mice, ${data.rows.toLocaleString()} observations after the cleaning rule removed ${data.dropped.join(', ')}. Every figure was produced by the CI run.` },
    { selector: '#s-final', title: 'Outliers by a rule', body: 'Final volumes per regimen with the 1.5 × IQR rule applied and its bounds printed; the one outlier is named with its value.' },
    { selector: '#s-tests', title: 'Tests, not adjectives', body: `ANOVA says the four regimens differ (F ${data.anovaF.toFixed(1)}); Tukey says which pairs. The weight-volume regression reports r = ${data.regressionR.toFixed(3)} — the earlier README claimed 0.84, which these files do not support.` },
    { selector: '#s-survival', title: 'Time in study, properly', body: 'Kaplan-Meier with censoring at day 45 and a log-rank test against placebo, instead of counting "deaths" from a table.' }
  ]
});
shell.refreshKpis();
